const POINTS_PER_TAPCO = 3500;
const POINTS_PER_TAPCO_DEPOSIT = 5000;
const MAX_WEEKLY_WITHDRAW_POINTS = 7000;
const TAPCO_MIN_WITHDRAW = 25;
const MIN_WITHDRAW_POINTS = TAPCO_MIN_WITHDRAW * POINTS_PER_TAPCO; // 87500

module.exports = {
	POINTS_PER_TAPCO,
	POINTS_PER_TAPCO_DEPOSIT,
	MAX_WEEKLY_WITHDRAW_POINTS,
	TAPCO_MIN_WITHDRAW,
	MIN_WITHDRAW_POINTS
};
